# Generated by Django 4.1.7 on 2023-04-19 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('phone', models.IntegerField()),
                ('detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource_management.staffdetail', verbose_name='thông tin chi tiết')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tài khoản đăng nhập')),
            ],
            options={
                'verbose_name': 'nhân viên',
                'verbose_name_plural': 'nhân viên',
            },
        ),
    ]
