# Generated by Django 4.1.7 on 2023-04-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'nhân viên', 'verbose_name_plural': 'nhân viên'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Tên'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Họ'),
            preserve_default=False,
        ),
    ]
