# Generated by Django 4.1.7 on 2023-04-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0002_alter_staff_options_remove_staff_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Họ và tên'),
            preserve_default=False,
        ),
    ]
