# Generated by Django 4.1.7 on 2023-05-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0002_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
