# Generated by Django 4.1.7 on 2023-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0003_staff_email_alter_staff_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='ảnh đại diện'),
        ),
    ]
