# Generated by Django 4.1.7 on 2023-05-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0004_staff_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
