# Generated by Django 4.1.7 on 2023-05-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0006_staff_phone_staff_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffDetail',
            new_name='Department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='detail',
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource_management.department', verbose_name='Khoa/Phòng'),
        ),
    ]
