# Generated by Django 4.1.7 on 2023-05-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0010_staff_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nation',
            field=models.CharField(blank=True, default='Kinh', max_length=10, null=True, verbose_name='dân tộc'),
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='số CMND/CCCD'),
        ),
        migrations.AddField(
            model_name='staff',
            name='religion',
            field=models.CharField(blank=True, default='Không', max_length=20, null=True, verbose_name='tôn giáo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='địa chỉ hiện tại'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Nam'), ('f', 'Nữ')], max_length=1, null=True, verbose_name='giới tính'),
        ),
    ]
