# Generated by Django 4.1.7 on 2023-05-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0011_staff_nation_staff_personal_id_staff_religion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='religion',
        ),
    ]
