# Generated by Django 4.1.7 on 2023-05-18 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource_management', '0012_remove_staff_nation_remove_staff_personal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tên nhóm')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='thời gian tạo')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('role', models.IntegerField(choices=[(0, 'Thành viên'), (1, 'Trưởng nhóm'), (2, 'Phó nhóm')], default=0, verbose_name='vị trí')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource_management.team', verbose_name='nhóm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nhân viên')),
            ],
        ),
    ]
