# Generated by Django 4.1.7 on 2023-05-18 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0014_alter_staffteam_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffteam',
            name='user',
        ),
        migrations.AddField(
            model_name='staffteam',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='human_resource_management.staff', verbose_name='nhân viên'),
            preserve_default=False,
        ),
    ]
