# Generated by Django 4.1.7 on 2023-05-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0016_rename_member_staffteam_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffteam',
            unique_together={('staff', 'team')},
        ),
    ]
