# Generated by Django 4.1.7 on 2023-04-05 00:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resource_management', '0003_remove_staff_first_name_remove_staff_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(choices=[(1, 'Chương 1'), (2, 'Chương 2'), (3, 'Chương 3'), (4, 'Chương 4'), (5, 'Chương 5'), (6, 'Chương 6'), (7, 'Chương 7'), (8, 'Chương 8'), (9, 'Chương 9'), (10, 'Chương 10')], verbose_name='chương')),
                ('title', models.TextField(verbose_name='tiêu đề')),
            ],
            options={
                'verbose_name': 'chương',
                'verbose_name_plural': 'chương',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'tiểu mục trong tiêu chí',
                'verbose_name_plural': 'tiểu mục trong tiêu chí',
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_criteria', models.IntegerField(choices=[(1, 'Mục 1'), (2, 'Mục 2'), (3, 'Mục 3'), (4, 'Mục 4'), (5, 'Mục 5'), (6, 'Mục 6')], verbose_name='mục')),
                ('title', models.TextField(verbose_name='tiêu đề')),
                ('legal_basis', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='căn cứ, đề xuất, ý nghĩa')),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ghi chú')),
            ],
            options={
                'verbose_name': 'tiêu chí',
                'verbose_name_plural': 'tiêu chí',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='doccuments/')),
            ],
            options={
                'verbose_name': 'file đính kèm',
                'verbose_name_plural': 'file đính kèm',
            },
        ),
        migrations.CreateModel(
            name='HQMMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now=True)),
                ('role', models.IntegerField(choices=[(1, 'Quản lý'), (2, 'Thành viên')], verbose_name='Vai trò')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource_management.staff', verbose_name='nhân viên')),
            ],
            options={
                'verbose_name': 'thành viên nhóm QLCLBV',
                'verbose_name_plural': 'thành viên nhóm QLCLBV',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'ảnh đính kèm',
                'verbose_name_plural': 'ảnh đính kèm',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'Phần A'), ('B', 'Phần B'), ('C', 'Phần C'), ('D', 'Phần D'), ('E', 'Phần E')], max_length=1, verbose_name='phần')),
                ('title', models.TextField(verbose_name='tiêu đề')),
            ],
            options={
                'verbose_name': 'phần',
                'verbose_name_plural': 'phần',
            },
        ),
        migrations.CreateModel(
            name='ResponserCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateField(auto_now=True, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Phụ trách chính'), (2, 'Phụ tránh chung')], verbose_name='vai trò')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ghi chú')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.condition', verbose_name='tiểu mục')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.hqmmember', verbose_name='người phụ trách')),
            ],
            options={
                'verbose_name': 'người phụ trách tiểu mục',
                'verbose_name_plural': 'người phụ trách tiểu mục',
            },
        ),
        migrations.CreateModel(
            name='Responser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateField(auto_now=True, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Phụ trách chính'), (2, 'Phụ tránh chung')], verbose_name='vai trò')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='ghi chú')),
                ('evalution_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='tiêu chí')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.hqmmember', verbose_name='thành viên')),
            ],
            options={
                'verbose_name': 'người phụ trách tiêu chí',
                'verbose_name_plural': 'người phụ trách tiêu chí',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], verbose_name='mức độ đánh giá')),
                ('evaluation_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='tiêu chí')),
            ],
            options={
                'verbose_name': 'mức chất lượng',
                'verbose_name_plural': 'mức chất lượng',
            },
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='files',
            field=models.ManyToManyField(blank=True, to='hospital_quality_management.file', verbose_name='file căn cứ'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='section_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.chapter', verbose_name='phần, chương'),
        ),
        migrations.AddField(
            model_name='condition',
            name='evaluation_criteria_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.level', verbose_name='mức chất lượng'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.section', verbose_name='phần'),
        ),
        migrations.CreateModel(
            name='AssessmentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('is_pass', models.BooleanField(default=False, verbose_name='đạt hay chưa?')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ghi chú')),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.condition', verbose_name='tiểu mục')),
                ('files', models.ManyToManyField(blank=True, to='hospital_quality_management.file', verbose_name='file đính kèm')),
                ('images', models.ManyToManyField(blank=True, to='hospital_quality_management.image', verbose_name='ảnh đính kèm')),
                ('responser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.hqmmember', verbose_name='người đánh giá')),
            ],
            options={
                'verbose_name': 'đánh giá tiểu mục',
                'verbose_name_plural': 'đánh giá tiểu mục',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='thời gian tạo')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='thòi gian cập nhật')),
                ('level', models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], verbose_name='mức đánh giá')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú')),
                ('evaluation_criteria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='tiêu chí')),
                ('responser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.hqmmember', verbose_name='người đánh giá')),
            ],
            options={
                'verbose_name': 'đánh giá tiêu chí',
                'verbose_name_plural': 'đánh giá tiêu chí',
            },
        ),
    ]
