# Generated by Django 4.1.7 on 2023-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='index',
            field=models.IntegerField(),
        ),
    ]
