# Generated by Django 4.1.7 on 2023-04-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responser',
            old_name='user',
            new_name='member',
        ),
    ]
