# Generated by Django 4.1.7 on 2023-03-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0002_alter_chapter_index_alter_evaluationcriteria_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pre_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.section'),
            preserve_default=False,
        ),
    ]
