# Generated by Django 4.1.7 on 2023-06-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0003_hqmdashboard_manager_ec_hqmdashboard_member_ec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hqmmember',
            name='role',
        ),
    ]
