# Generated by Django 4.1.7 on 2023-03-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0003_chapter_pre_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='pre_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.chapter'),
            preserve_default=False,
        ),
    ]
