# Generated by Django 4.1.7 on 2023-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0004_evaluationcriteria_pre_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
