# Generated by Django 4.1.7 on 2023-06-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0004_remove_hqmmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqmdashboard',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Thời gian hoàn thành dự kiến'),
        ),
        migrations.AlterField(
            model_name='hqmdashboard',
            name='evaluation_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', unique=True, verbose_name='tiêu chí'),
        ),
        migrations.RemoveField(
            model_name='hqmdashboard',
            name='member_ec',
        ),
        migrations.AlterField(
            model_name='hqmdashboard',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='giải pháp cần thực hiện'),
        ),
        migrations.AlterField(
            model_name='hqmdashboard',
            name='result',
            field=models.BooleanField(blank=True, choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], null=True, verbose_name='kết quả'),
        ),
        migrations.AddField(
            model_name='hqmdashboard',
            name='member_ec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
