# Generated by Django 4.1.7 on 2023-03-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0005_alter_evaluationcriteria_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='legal_basis',
        ),
    ]
