# Generated by Django 4.1.7 on 2023-03-30 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0006_remove_evaluationcriteria_legal_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='legal_basis',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
