# Generated by Django 4.1.7 on 2023-03-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0008_file_evaluationcriteria_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
