# Generated by Django 4.1.7 on 2023-03-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0009_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='pre_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria'),
            preserve_default=False,
        ),
    ]
