# Generated by Django 4.1.7 on 2023-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0012_alter_evaluationcriteria_files_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(choices=[(1, 'Chương 1'), (2, 'Chương 2'), (3, 'Chương 3'), (4, 'Chương 4'), (5, 'Chương 5'), (6, 'Chương 6'), (7, 'Chương 7'), (8, 'Chương 8'), (9, 'Chương 9'), (10, 'Chương 10'), (11, 'Chương 11'), (12, 'Chương 12'), (13, 'Chương 13'), (14, 'Chương 14'), (15, 'Chương 15'), (16, 'Chương 16')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='index',
            field=models.CharField(choices=[('A', 'Phần A'), ('B', 'Phần B'), ('C', 'Phần C'), ('D', 'Phần D'), ('E', 'Phần E'), ('F', 'Phần F'), ('G', 'Phần G')], max_length=1),
        ),
    ]
