# Generated by Django 4.1.7 on 2023-03-31 02:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0013_alter_chapter_index_alter_section_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Chương', 'verbose_name_plural': 'Chương'},
        ),
        migrations.AlterModelOptions(
            name='evaluationcriteria',
            options={'verbose_name': 'Tiêu chí', 'verbose_name_plural': 'Tiêu chí'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File đính kèm', 'verbose_name_plural': 'File đính kèm'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Mức tiêu chí', 'verbose_name_plural': 'Mức tiêu chí'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Phần', 'verbose_name_plural': 'Phần'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(choices=[(1, 'Chương 1'), (2, 'Chương 2'), (3, 'Chương 3'), (4, 'Chương 4'), (5, 'Chương 5'), (6, 'Chương 6'), (7, 'Chương 7'), (8, 'Chương 8'), (9, 'Chương 9'), (10, 'Chương 10'), (11, 'Chương 11'), (12, 'Chương 12'), (13, 'Chương 13'), (14, 'Chương 14'), (15, 'Chương 15'), (16, 'Chương 16')], verbose_name='Chương'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pre_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.section', verbose_name='Phần'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='index',
            field=models.IntegerField(choices=[(1, 'Mục 1'), (2, 'Mục 2'), (3, 'Mục 3'), (4, 'Mục 4'), (5, 'Mục 5'), (6, 'Mục 6'), (7, 'Mục 7'), (8, 'Mục 8'), (9, 'Mục 9'), (10, 'Mục 10'), (11, 'Mục 11'), (12, 'Mục 12'), (13, 'Mục 13'), (14, 'Mục 14'), (15, 'Mục 15'), (16, 'Mục 16'), (17, 'Mục 17'), (18, 'Mục 18'), (19, 'Mục 19')], verbose_name='Mục'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='legal_basis',
            field=ckeditor.fields.RichTextField(verbose_name='Căn cứ, đề xuất, ý nghĩa'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='pre_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.chapter', verbose_name='Phần, Chương'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='title',
            field=models.TextField(verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='level',
            name='index',
            field=models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5'), (6, 'Mức 6'), (7, 'Mức 7'), (8, 'Mức 8'), (9, 'Mức 9'), (10, 'Mức 10')], verbose_name='Mức độ đánh giá'),
        ),
        migrations.AlterField(
            model_name='level',
            name='pre_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='Tiêu chí'),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='section',
            name='index',
            field=models.CharField(choices=[('A', 'Phần A'), ('B', 'Phần B'), ('C', 'Phần C'), ('D', 'Phần D'), ('E', 'Phần E'), ('F', 'Phần F'), ('G', 'Phần G')], max_length=1, verbose_name='Phần'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(verbose_name='Tiêu đề'),
        ),
    ]
