# Generated by Django 4.1.7 on 2023-03-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0014_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(choices=[(1, 'Yêu cầu 1'), (2, 'Yêu cầu 2'), (3, 'Yêu cầu 3'), (4, 'Yêu cầu 4'), (5, 'Yêu cầu 5'), (6, 'Yêu cầu 6'), (7, 'Yêu cầu 7'), (8, 'Yêu cầu 8'), (9, 'Yêu cầu 9'), (10, 'Yêu cầu 10')], verbose_name='Yêu cầu')),
                ('title', models.TextField(verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Yêu cầu trong mức tiêu chí',
                'verbose_name_plural': 'Yêu cầu trong mức tiêu chí',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='request',
            field=models.ManyToManyField(blank=True, null=True, to='hospital_quality_management.request'),
        ),
    ]
