# Generated by Django 4.1.7 on 2023-03-31 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0015_request_level_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Bậc thang chất lượng', 'verbose_name_plural': 'Bậc thang chất lượng'},
        ),
        migrations.RemoveField(
            model_name='level',
            name='title',
        ),
    ]
