# Generated by Django 4.1.7 on 2023-03-31 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0016_alter_request_options_remove_level_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='request',
        ),
        migrations.AddField(
            model_name='request',
            name='pre_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.level', verbose_name='Tiêu chí'),
            preserve_default=False,
        ),
    ]
