# Generated by Django 4.1.7 on 2023-03-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0017_remove_level_request_request_pre_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(choices=[(1, 'Chương 1'), (2, 'Chương 2'), (3, 'Chương 3'), (4, 'Chương 4'), (5, 'Chương 5'), (6, 'Chương 6'), (7, 'Chương 7'), (8, 'Chương 8'), (9, 'Chương 9'), (10, 'Chương 10')], verbose_name='Chương'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='index',
            field=models.IntegerField(choices=[(1, 'Mục 1'), (2, 'Mục 2'), (3, 'Mục 3'), (4, 'Mục 4'), (5, 'Mục 5'), (6, 'Mục 6')], verbose_name='Mục'),
        ),
        migrations.AlterField(
            model_name='level',
            name='index',
            field=models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], verbose_name='Mức độ đánh giá'),
        ),
    ]
