# Generated by Django 4.1.7 on 2023-04-01 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0020_alter_requestlevel_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='legal_basis',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Căn cứ, đề xuất, ý nghĩa'),
        ),
    ]
