# Generated by Django 4.1.7 on 2023-04-02 00:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0021_alter_evaluationcriteria_legal_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
