# Generated by Django 4.1.7 on 2023-04-02 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_quality_management', '0022_evaluationcriteria_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Phụ trách chính'), (2, 'Phụ tránh chung')])),
                ('notes', models.TextField()),
                ('evalution_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='Tiêu chí')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
        ),
    ]
