# Generated by Django 4.1.7 on 2023-04-02 01:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_quality_management', '0024_alter_responser_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responser',
            options={'verbose_name': 'Người phụ trách', 'verbose_name_plural': 'Người phụ trách'},
        ),
        migrations.AddField(
            model_name='responser',
            name='time_created',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('notes', ckeditor.fields.RichTextField()),
                ('evalution_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='Tiêu chí')),
                ('files', models.ManyToManyField(blank=True, to='hospital_quality_management.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
        ),
    ]
