# Generated by Django 4.1.7 on 2023-04-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0025_alter_responser_options_responser_time_created_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Bậc thang từng mức chất lượng',
                'verbose_name_plural': 'Bậc thang từng mức chất lượng',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], verbose_name='Mức độ đánh giá')),
                ('pre_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='Tiêu chí')),
            ],
            options={
                'verbose_name': 'Mức chất lượng',
                'verbose_name_plural': 'Mức chất lượng',
            },
        ),
        migrations.DeleteModel(
            name='RequestLevel',
        ),
        migrations.AddField(
            model_name='condition',
            name='pre_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.level', verbose_name='Mức chất lượng'),
        ),
    ]
