# Generated by Django 4.1.7 on 2023-04-03 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_quality_management', '0026_condition_level_delete_requestlevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponserCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateField(auto_now=True, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Phụ trách chính'), (2, 'Phụ tránh chung')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('evalution_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.condition', verbose_name='Tiểu mục')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Người phụ trách tiểu mục',
                'verbose_name_plural': 'Người phụ tiểu mục',
            },
        ),
    ]
