# Generated by Django 4.1.7 on 2023-04-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0027_responsercondition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsercondition',
            options={'verbose_name': 'Người phụ trách tiểu mục', 'verbose_name_plural': 'Người phụ trách tiểu mục'},
        ),
        migrations.RenameField(
            model_name='responsercondition',
            old_name='evalution_criteria',
            new_name='condition',
        ),
    ]
