# Generated by Django 4.1.7 on 2023-04-03 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0029_alter_condition_options_alter_responser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selfassessment',
            options={'verbose_name': 'Tự đánh giá', 'verbose_name_plural': 'Tự đánh giá'},
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='evaluation_criteria_level',
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='is_apply',
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='evaluation_criteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='Tiêu chí'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='level',
            field=models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], default=1),
            preserve_default=False,
        ),
    ]
