# Generated by Django 4.1.7 on 2023-04-03 04:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0030_alter_selfassessment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassessment',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
