# Generated by Django 4.1.7 on 2023-04-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0031_alter_selfassessment_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proof',
            options={'verbose_name': 'Bằng chứng đánh giá', 'verbose_name_plural': 'Bằng chứng đánh giá'},
        ),
        migrations.RemoveField(
            model_name='proof',
            name='evalution_criteria',
        ),
        migrations.AddField(
            model_name='proof',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.condition', verbose_name='Tiểu mục'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='level',
            field=models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], verbose_name='Mức đánh giá'),
        ),
    ]
