# Generated by Django 4.1.7 on 2023-04-03 09:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_quality_management', '0032_alter_proof_options_remove_proof_evalution_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'ảnh đính kèm',
                'verbose_name_plural': 'ảnh đính kèm',
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'chương', 'verbose_name_plural': 'chương'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'tiểu mục trong tiêu chí', 'verbose_name_plural': 'tiểu mục trong tiêu chí'},
        ),
        migrations.AlterModelOptions(
            name='evaluationcriteria',
            options={'verbose_name': 'tiêu chí', 'verbose_name_plural': 'tiêu chí'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file đính kèm', 'verbose_name_plural': 'file đính kèm'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'mức chất lượng', 'verbose_name_plural': 'mức chất lượng'},
        ),
        migrations.AlterModelOptions(
            name='proof',
            options={'verbose_name': 'bằng chứng đánh giá', 'verbose_name_plural': 'bằng chứng đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='responser',
            options={'verbose_name': 'người phụ trách tiêu chí', 'verbose_name_plural': 'người phụ trách tiêu chí'},
        ),
        migrations.AlterModelOptions(
            name='responsercondition',
            options={'verbose_name': 'người phụ trách tiểu mục', 'verbose_name_plural': 'người phụ trách tiểu mục'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'phần', 'verbose_name_plural': 'phần'},
        ),
        migrations.AlterModelOptions(
            name='selfassessment',
            options={'verbose_name': 'tự đánh giá', 'verbose_name_plural': 'tự đánh giá'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='index',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='pre_index',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='pre_index',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='index',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='pre_index',
        ),
        migrations.RemoveField(
            model_name='level',
            name='pre_index',
        ),
        migrations.RemoveField(
            model_name='section',
            name='index',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter',
            field=models.IntegerField(choices=[(1, 'Chương 1'), (2, 'Chương 2'), (3, 'Chương 3'), (4, 'Chương 4'), (5, 'Chương 5'), (6, 'Chương 6'), (7, 'Chương 7'), (8, 'Chương 8'), (9, 'Chương 9'), (10, 'Chương 10')], default=1, verbose_name='chương'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.section', verbose_name='phần'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='evaluation_criteria_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.level', verbose_name='mức chất lượng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='evaluation_criteria',
            field=models.IntegerField(choices=[(1, 'Mục 1'), (2, 'Mục 2'), (3, 'Mục 3'), (4, 'Mục 4'), (5, 'Mục 5'), (6, 'Mục 6')], default=1, verbose_name='mục'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='section_chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.chapter', verbose_name='phần, chương'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='evaluation_criteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='tiêu chí'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section',
            field=models.CharField(choices=[('A', 'Phần A'), ('B', 'Phần B'), ('C', 'Phần C'), ('D', 'Phần D'), ('E', 'Phần E')], default=1, max_length=1, verbose_name='phần'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(verbose_name='tiêu đề'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='files',
            field=models.ManyToManyField(blank=True, to='hospital_quality_management.file', verbose_name='file căn cứ'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='legal_basis',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='căn cứ, đề xuất, ý nghĩa'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ghi chú'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='title',
            field=models.TextField(verbose_name='tiêu đề'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], verbose_name='mức độ đánh giá'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.condition', verbose_name='tiểu mục'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='files',
            field=models.ManyToManyField(blank=True, to='hospital_quality_management.file', verbose_name='file đính kèm'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proof',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='người tải lên'),
        ),
        migrations.AlterField(
            model_name='responser',
            name='evalution_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='tiêu chí'),
        ),
        migrations.AlterField(
            model_name='responser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Phụ trách chính'), (2, 'Phụ tránh chung')], verbose_name='vai trò'),
        ),
        migrations.AlterField(
            model_name='responser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nhân viên'),
        ),
        migrations.AlterField(
            model_name='responsercondition',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.condition', verbose_name='tiểu mục'),
        ),
        migrations.AlterField(
            model_name='responsercondition',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ghi chú'),
        ),
        migrations.AlterField(
            model_name='responsercondition',
            name='role',
            field=models.IntegerField(choices=[(1, 'Phụ trách chính'), (2, 'Phụ tránh chung')], verbose_name='vai trò'),
        ),
        migrations.AlterField(
            model_name='responsercondition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nhân viên'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(verbose_name='tiêu đề'),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='thòi gian cập nhật'),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='evaluation_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='tiêu chí'),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='level',
            field=models.IntegerField(choices=[(1, 'Mức 1'), (2, 'Mức 2'), (3, 'Mức 3'), (4, 'Mức 4'), (5, 'Mức 5')], verbose_name='mức đánh giá'),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='người đánh giá'),
        ),
        migrations.AddField(
            model_name='proof',
            name='images',
            field=models.ManyToManyField(blank=True, to='hospital_quality_management.image', verbose_name='ảnh đính kèm'),
        ),
    ]
