# Generated by Django 4.1.7 on 2023-04-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0034_alter_selfassessment_evaluation_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ghi chú'),
        ),
    ]
