# Generated by Django 4.1.7 on 2023-04-04 00:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0035_alter_evaluationcriteria_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ghi chú'),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
