# Generated by Django 4.1.7 on 2023-04-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0036_alter_evaluationcriteria_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responser',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
