# Generated by Django 4.1.7 on 2023-04-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0037_alter_responser_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassessment',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú'),
        ),
    ]
