# Generated by Django 4.1.7 on 2023-04-04 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0002_alter_staff_options_remove_staff_name_and_more'),
        ('hospital_quality_management', '0039_remove_proof_files_proof_file_remove_proof_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQMMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource_management.staff', verbose_name='nhân viên')),
            ],
            options={
                'verbose_name': 'thành viên nhóm quản lý chất lượng bệnh viện',
                'verbose_name_plural': 'thành viên nhóm quản lý chất lượng bệnh viện',
            },
        ),
    ]
