# Generated by Django 4.1.7 on 2023-04-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0040_hqmmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqmmember',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='hqmmember',
            name='role',
            field=models.IntegerField(choices=[(1, 'Quản lý'), (2, 'Thành viên')], default=1, verbose_name='Vai trò'),
            preserve_default=False,
        ),
    ]
