# Generated by Django 4.1.7 on 2023-04-04 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0041_hqmmember_note_hqmmember_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hqmmember',
            options={'verbose_name': 'thành viên nhóm QLCLBV', 'verbose_name_plural': 'thành viên nhóm QLCLBV'},
        ),
        migrations.RemoveField(
            model_name='responsercondition',
            name='user',
        ),
        migrations.AddField(
            model_name='responsercondition',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.hqmmember', verbose_name='người phụ trách'),
            preserve_default=False,
        ),
    ]
