# Generated by Django 4.1.7 on 2023-04-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0042_alter_hqmmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.hqmmember', verbose_name='người chịu trách nhiệm'),
        ),
    ]
