# Generated by Django 4.1.7 on 2023-04-04 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0044_alter_responser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.hqmmember', verbose_name='người đánh giá'),
        ),
    ]
