# Generated by Django 4.1.7 on 2023-04-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0046_alter_selfassessment_evaluation_criteria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selfassessment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='evaluation_criteria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.evaluationcriteria', verbose_name='tiêu chí'),
        ),
    ]
