# Generated by Django 4.1.7 on 2023-04-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0047_alter_selfassessment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='đạt hay chưa?'),
        ),
    ]
