# Generated by Django 4.1.7 on 2023-04-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0048_proof_is_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessmentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('is_pass', models.BooleanField(default=False, verbose_name='đạt hay chưa?')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ghi chú')),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.condition', verbose_name='Tiểu mục')),
            ],
        ),
    ]
