# Generated by Django 4.1.7 on 2023-04-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0050_alter_selfassessmentcondition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassessmentcondition',
            name='proofs',
        ),
        migrations.AddField(
            model_name='selfassessmentcondition',
            name='proofs',
            field=models.ManyToManyField(blank=True, null=True, to='hospital_quality_management.proof', verbose_name='bằng chứng đánh giá'),
        ),
    ]
