# Generated by Django 4.1.7 on 2023-04-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0051_remove_selfassessmentcondition_proofs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('is_pass', models.BooleanField(default=False, verbose_name='đạt hay chưa?')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ghi chú')),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.condition', verbose_name='tiểu mục')),
            ],
            options={
                'verbose_name': 'tự đánh giá',
                'verbose_name_plural': 'tự đánh giá',
            },
        ),
        migrations.RenameModel(
            old_name='SelfAssessment',
            new_name='Assessment',
        ),
        migrations.RemoveField(
            model_name='selfassessmentcondition',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='selfassessmentcondition',
            name='proofs',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='user',
            new_name='responser',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='doccuments/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Proof',
        ),
        migrations.DeleteModel(
            name='SelfAssessmentCondition',
        ),
        migrations.AddField(
            model_name='assessmentcondition',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='hospital_quality_management.file', verbose_name='file đính kèm'),
        ),
        migrations.AddField(
            model_name='assessmentcondition',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='hospital_quality_management.image', verbose_name='ảnh đính kèm'),
        ),
        migrations.AddField(
            model_name='assessmentcondition',
            name='responser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_quality_management.hqmmember', verbose_name='người đánh giá'),
        ),
    ]
