# Generated by Django 4.1.7 on 2023-04-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_quality_management', '0052_assessmentcondition_rename_selfassessment_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcondition',
            name='files',
            field=models.ManyToManyField(blank=True, to='hospital_quality_management.file', verbose_name='file đính kèm'),
        ),
        migrations.AlterField(
            model_name='assessmentcondition',
            name='images',
            field=models.ManyToManyField(blank=True, to='hospital_quality_management.image', verbose_name='ảnh đính kèm'),
        ),
    ]
