# Generated by Django 4.1.7 on 2023-05-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Họ và tên')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Số điện thoại')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='ảnh đại diện')),
                ('birth_of_date', models.DateField(blank=True, null=True, verbose_name='ngày sinh')),
            ],
            options={
                'verbose_name': 'thành viên',
                'verbose_name_plural': 'thành viên',
            },
        ),
    ]
