# Generated by Django 4.1.7 on 2023-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_full_name_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_of_date',
            field=models.DateField(blank=True, null=True, verbose_name='ngày sinh'),
        ),
    ]
