# Generated by Django 4.1.7 on 2023-05-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_profile_profiledetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileDetail',
        ),
    ]
