# Generated by Django 4.1.7 on 2023-04-21 02:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='tên')),
                ('description', models.CharField(max_length=200, verbose_name='mô tả ngắn')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='ảnh đại diện')),
            ],
            options={
                'verbose_name': 'tác giả',
                'verbose_name_plural': 'tác giả',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='tên bài viết')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='có phải bài viết nổi bật')),
                ('is_public', models.BooleanField(default=True, verbose_name='có hiển thị bài viết')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='nội dung')),
                ('youtube_url', models.URLField(blank=True, help_text='dán url video youtube vào đây', max_length=40, null=True, verbose_name='URL video youtube')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='post-covers/', verbose_name='ảnh bìa')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='số lượt xem')),
                ('like', models.IntegerField(blank=True, default=0, null=True, verbose_name='số lượt like')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='tác giả')),
            ],
            options={
                'verbose_name': 'bài viết',
                'verbose_name_plural': 'bài viết',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='trích dẫn')),
                ('author', models.CharField(max_length=50, verbose_name='tác giả')),
            ],
            options={
                'verbose_name': 'trích dẫn',
                'verbose_name_plural': 'trích dẫn',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tên đầy đủ')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='mô tả')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover-tag/', verbose_name='ảnh bìa')),
                ('parrent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.tag', verbose_name='danh mục cha')),
            ],
            options={
                'verbose_name': 'danh mục',
                'verbose_name_plural': 'danh mục',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='banner', max_length=200, verbose_name='tiêu đề')),
                ('cover', models.ImageField(help_text='ảnh slide nên có tỉ lệ cao:rộng là 1:4 để đẹp nhất ', upload_to='slides/', verbose_name='ảnh slide')),
                ('is_show', models.BooleanField(default=True, verbose_name='hiển thị trang chủ')),
                ('created_time', models.TimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='bài viết liên kết')),
            ],
            options={
                'verbose_name': 'slide trang chủ',
                'verbose_name_plural': 'slide trang chủ',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag', verbose_name='danh mục'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'bình luận',
                'verbose_name_plural': 'bình luận',
            },
        ),
    ]
