# Generated by Django 4.1.7 on 2023-04-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
