# Generated by Django 4.1.7 on 2023-04-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_tag_cover_remove_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_highlight',
        ),
    ]
