# Generated by Django 4.1.7 on 2023-04-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_post_is_highlight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
