# Generated by Django 4.1.7 on 2023-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parrent_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='có ghim bài viết'),
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
