# Generated by Django 4.1.7 on 2023-04-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=1, max_length=1000, verbose_name='tóm tắt ngắn'),
            preserve_default=False,
        ),
    ]
