# Generated by Django 4.1.7 on 2023-04-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='ảnh bìa sẽ tự động resize về kích thước 768 x 432', null=True, upload_to='post-covers/', verbose_name='ảnh bìa'),
        ),
    ]
