# Generated by Django 4.1.7 on 2023-04-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_post_user_alter_post_author_alter_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('private', 'Chỉ mình tôi'), ('staff', 'Nhân viên'), ('public', 'Mọi người')], default='public', max_length=10, verbose_name='trạng thái bài viết'),
        ),
    ]
