# Generated by Django 4.1.7 on 2023-05-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_post_cover'),
        ('news', '0012_post_category_alter_post_tags'),
    ]

    operations = [
    ]
