# Generated by Django 4.1.7 on 2023-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_merge_20230501_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plaintext_content',
            field=models.TextField(blank=True, null=True, verbose_name='plain text of content'),
        ),
    ]
