# Generated by Django 4.1.7 on 2023-05-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_tag_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, help_text='ảnh bìa sẽ tự động resize về kích thước 768 x 432', null=True, upload_to='tag-covers/', verbose_name='ảnh bìa'),
        ),
    ]
