# Generated by Django 4.1.7 on 2023-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_post_status_posteditor_postchecker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag', verbose_name='thẻ'),
        ),
    ]
