# Generated by Django 4.1.7 on 2023-05-19 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0020_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tài khoản'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Nháp'), ('private', 'Ẩn'), ('staff', 'Nhân viên'), ('public', 'Mọi người')], default='private', max_length=10, null=True, verbose_name='trạng thái bài viết'),
        ),
    ]
