# Generated by Django 4.1.7 on 2023-05-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_alter_post_author_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tên'),
        ),
    ]
